export const regionStatusData = {
  statusGrade: [
    {
      name: "용산동2가",
      normal: 30,
      info: 10,
      warning: 15,
      danger: 20,
    },
    {
      name: "이태원동",
      normal: 25,
      info: 8,
      warning: 10,
      danger: 18,
    },
    {
      name: "한남동",
      normal: 25,
      info: 8,
      warning: 12,
      danger: 5,
    },
    {
      name: "용산동4가",
      normal: 20,
      info: 3,
      warning: 5,
      danger: 2,
    },
    {
      name: "보광동",
      normal: 28,
      info: 6,
      warning: 7,
      danger: 3,
    },
    {
      name: "주성동",
      normal: 22,
      info: 5,
      warning: 10,
      danger: 5,
    },
  ],

  lastActivity: [
    {
      name: "용산동2가",
      within_24h: 40,
      "24_to_48h": 10,
      "48_to_72h": 5,
      over_72h: 20,
    },
    {
      name: "이태원동",
      within_24h: 35,
      "24_to_48h": 12,
      "48_to_72h": 6,
      over_72h: 8,
    },
    {
      name: "한남동",
      within_24h: 30,
      "24_to_48h": 15,
      "48_to_72h": 10,
      over_72h: 5,
    },
    {
      name: "용산동4가",
      within_24h: 20,
      "24_to_48h": 6,
      "48_to_72h": 2,
      over_72h: 2,
    },
    {
      name: "보광동",
      within_24h: 25,
      "24_to_48h": 10,
      "48_to_72h": 5,
      over_72h: 4,
    },
    {
      name: "주성동",
      within_24h: 18,
      "24_to_48h": 10,
      "48_to_72h": 8,
      over_72h: 6,
    },
  ],

  abnormalSigns: [
    {
      name: "용산동2가",
      sleep_disorder: 10,
      cognitive_decline: 15,
      lethargy: 5,
      inactivity: 20,
    },
    {
      name: "이태원동",
      sleep_disorder: 8,
      cognitive_decline: 12,
      lethargy: 4,
      inactivity: 10,
    },
    {
      name: "한남동",
      sleep_disorder: 5,
      cognitive_decline: 10,
      lethargy: 7,
      inactivity: 8,
    },
    {
      name: "용산동4가",
      sleep_disorder: 3,
      cognitive_decline: 4,
      lethargy: 2,
      inactivity: 5,
    },
    {
      name: "보광동",
      sleep_disorder: 6,
      cognitive_decline: 5,
      lethargy: 3,
      inactivity: 4,
    },
    {
      name: "주성동",
      sleep_disorder: 7,
      cognitive_decline: 8,
      lethargy: 6,
      inactivity: 7,
    },
  ],
};
