export * from "./home";
export * from "./login";
export * from "./care";
export * from "./manager";
export * from "./senior-detail";
export * from "./senior";
export * from "./system";
export * from "./care-post";
export * from "./care-detail";
