import type { PersonStatusType } from "../types";

export const personStatusData: PersonStatusType[] = [
  {
    id: 1,
    name: "이정선",
    manager: "황지원",
    level: "정상",
    lastActive: "7시간 전",
    abnormalSign: null,
  },
  {
    id: 2,
    name: "김순자",
    manager: "하수민",
    level: "정상",
    lastActive: "12시간 전",
    abnormalSign: null,
  },
  {
    id: 3,
    name: "이영희",
    manager: "황지원",
    level: "관심",
    lastActive: "8시간 전",
    abnormalSign: "수면 장애 의심",
  },
  {
    id: 4,
    name: "박정숙",
    manager: "황지원",
    level: "주의",
    lastActive: "1시간 전",
    abnormalSign: "인지 저하 의심",
  },
  {
    id: 5,
    name: "최복자",
    manager: "고은서",
    level: "위험",
    lastActive: "241시간 전",
    abnormalSign: "장시간 미활동",
  },
  {
    id: 6,
    name: "유기순",
    manager: "고은서",
    level: "주의",
    lastActive: "27시간 전",
    abnormalSign: "인지 저하 의심",
  },
  {
    id: 7,
    name: "장용수",
    manager: "김수현",
    level: "관심",
    lastActive: "7시간 전",
    abnormalSign: "무기력증 의심",
  },
  {
    id: 8,
    name: "조병철",
    manager: "황지원",
    level: "정상",
    lastActive: "12시간 전",
    abnormalSign: null,
  },
  {
    id: 9,
    name: "한말순",
    manager: "황지원",
    level: "정상",
    lastActive: "3시간 전",
    abnormalSign: null,
  },
  {
    id: 10,
    name: "오재근",
    manager: "정지율",
    level: "정상",
    lastActive: "7시간 전",
    abnormalSign: null,
  },
  {
    id: 11,
    name: "정영남",
    manager: "정지율",
    level: "위험",
    lastActive: "25시간 전",
    abnormalSign: "무기력증 의심",
  },
];
